<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_class</name>
   <tag></tag>
   <elementGuidId>196df602-e289-475c-9e7e-82e309e8d0d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(@class,'${class}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(@class,'${class}')]</value>
      <webElementGuid>d53e21fe-0e0f-4b10-aab2-473e3fc51001</webElementGuid>
   </webElementProperties>
</WebElementEntity>
