<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ads_close_button</name>
   <tag></tag>
   <elementGuidId>bedefe21-a075-4169-942f-16da820ed552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;popup-member&quot;]/div//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;popup-member&quot;]/div//button</value>
      <webElementGuid>9c045818-bfc9-4bed-ad13-3a630bb3127f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
