<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_color_option_pos</name>
   <tag></tag>
   <elementGuidId>0d250534-8fe5-4417-9732-a832246ad1f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='homepage-products'][${section-pos}]//*[@data-slick-index='${index-pro-pos}']//*[@data-option-id='color']/div[${color-pos}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
