<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>id</name>
   <tag></tag>
   <elementGuidId>85421684-f8b5-4198-98a5-442db4d2cbce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='${id}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='${id}']</value>
      <webElementGuid>1d8bf537-ba4e-4839-9c67-8985eb650fdb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
