<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>id_span_class</name>
   <tag></tag>
   <elementGuidId>7401b681-d747-4edc-983a-41de87c77400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='${id}']//span[contains(@class,'${class}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='${id}']//span[contains(@class,'${class}')]</value>
      <webElementGuid>b54639fd-fcf4-4eb2-800b-4ea745e79feb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
