<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_class</name>
   <tag></tag>
   <elementGuidId>73a830c5-af4e-4cb0-8ef2-c5bcf25fb5d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@class,'${class}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@class,'${class}')]</value>
      <webElementGuid>8c3ce392-3fbb-4f3b-ae91-9e12c5b2d819</webElementGuid>
   </webElementProperties>
</WebElementEntity>
