<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ads_close_button</name>
   <tag></tag>
   <elementGuidId>bedefe21-a075-4169-942f-16da820ed552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;site-wrapper&quot;]/div[1]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;site-wrapper&quot;]/div[1]//button</value>
      <webElementGuid>1432dfbc-9d15-46d2-a179-936ee41d8ce7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
