<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id_with_input_name</name>
   <tag></tag>
   <elementGuidId>10d8e0d1-2d80-44db-8c27-ed7e070444de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='${id}']//input[@name='${name}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='${id}']//input[@name='${name}']</value>
      <webElementGuid>3f06375f-9339-461e-8dcc-eb402369bdfc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
