<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quantity_product</name>
   <tag></tag>
   <elementGuidId>1df0fd22-0661-4672-a570-98d3fdbcdd68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[text()='${product-name}']//ancestor::div[@class='cart-item-content__wrapper']/div//div[@class='quantity-box']//input)[${same-product-order}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
